
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'IDENTIFIER INT INTEGER LBRACE LPAREN RBRACE RETURN RPAREN SEMICOLONprogram : functionfunction : INT IDENTIFIER LPAREN RPAREN LBRACE statement RBRACEexp : INTEGERstatement : RETURN exp SEMICOLON\n                  '
    
_lr_action_items = {'SEMICOLON':([10,11,],[-3,13,]),'RPAREN':([5,],[6,]),'LPAREN':([4,],[5,]),'$end':([1,3,12,],[0,-1,-2,]),'INTEGER':([8,],[10,]),'INT':([0,],[2,]),'RBRACE':([9,13,],[12,-4,]),'LBRACE':([6,],[7,]),'RETURN':([7,],[8,]),'IDENTIFIER':([2,],[4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([7,],[9,]),'function':([0,],[3,]),'program':([0,],[1,]),'exp':([8,],[11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> function','program',1,'p_program','c_parser.py',56),
  ('function -> INT IDENTIFIER LPAREN RPAREN LBRACE statement RBRACE','function',7,'p_function','c_parser.py',59),
  ('exp -> INTEGER','exp',1,'p_exp','c_parser.py',64),
  ('statement -> RETURN exp SEMICOLON','statement',3,'p_statement','c_parser.py',69),
]
